# Generated by Django 5.0.6 on 2024-07-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_marca"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cor",
            old_name="descricao",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="marca",
            old_name="descricao",
            new_name="nacionalidade",
        ),
        migrations.AddField(
            model_name="marca",
            name="nome",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
