# Generated by Django 5.0.6 on 2024-07-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_descricao_cor_nome_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cor",
            options={"verbose_name": "Cor", "verbose_name_plural": "Cores"},
        ),
    ]
